# Generated by Django 5.1.1 on 2024-09-15 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_alter_usuario_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='foto_perfil',
            field=models.CharField(default='foto_perfil_1.png', max_length=100),
        ),
    ]
