# Generated by Django 5.1.1 on 2024-09-12 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_alter_usuario_email'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True)),
                ('data_vencimento', models.DateField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atribuido_para', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_atribuidas', to='cadastro.usuario')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_criadas', to='cadastro.usuario')),
            ],
        ),
        migrations.DeleteModel(
            name='Board',
        ),
    ]
