# Generated by Django 5.1.1 on 2024-09-10 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_board_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='criado_em',
            new_name='data',
        ),
    ]
