# Generated by Django 5.1.1 on 2024-09-12 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_delete_board'),
        ('tasks', '0003_rename_criado_em_board_data'),
    ]

    operations = [
    ]
